// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	api.proto
	game.proto

It has these top-level messages:
	Error
	PlainResponse
	UserInfo
	MeResponse
	WorldInfo
	WorldsResponse
	WorldSettings
	WorldSettingsResponse
	ChunksResponse
*/
package messages

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Error struct {
	Code             *int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Text             *string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Error) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type PlainResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlainResponse) Reset()         { *m = PlainResponse{} }
func (m *PlainResponse) String() string { return proto.CompactTextString(m) }
func (*PlainResponse) ProtoMessage()    {}

func (m *PlainResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UserInfo struct {
	Name             *string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Email            *string  `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Worlds           []string `protobuf:"bytes,3,rep,name=worlds" json:"worlds,omitempty"`
	Role             *int32   `protobuf:"varint,4,opt,name=role" json:"role,omitempty"`
	DonorLvl         *int32   `protobuf:"varint,5,opt,name=donorLvl" json:"donorLvl,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}

func (m *UserInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *UserInfo) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *UserInfo) GetWorlds() []string {
	if m != nil {
		return m.Worlds
	}
	return nil
}

func (m *UserInfo) GetRole() int32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

func (m *UserInfo) GetDonorLvl() int32 {
	if m != nil && m.DonorLvl != nil {
		return *m.DonorLvl
	}
	return 0
}

type MeResponse struct {
	Error            *Error    `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Info             *UserInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *MeResponse) Reset()         { *m = MeResponse{} }
func (m *MeResponse) String() string { return proto.CompactTextString(m) }
func (*MeResponse) ProtoMessage()    {}

func (m *MeResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *MeResponse) GetInfo() *UserInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type WorldInfo struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Started          *int32  `protobuf:"varint,2,opt,name=started" json:"started,omitempty"`
	Players          *int32  `protobuf:"varint,3,opt,name=players" json:"players,omitempty"`
	Size             *int32  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WorldInfo) Reset()         { *m = WorldInfo{} }
func (m *WorldInfo) String() string { return proto.CompactTextString(m) }
func (*WorldInfo) ProtoMessage()    {}

func (m *WorldInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *WorldInfo) GetStarted() int32 {
	if m != nil && m.Started != nil {
		return *m.Started
	}
	return 0
}

func (m *WorldInfo) GetPlayers() int32 {
	if m != nil && m.Players != nil {
		return *m.Players
	}
	return 0
}

func (m *WorldInfo) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

type WorldsResponse struct {
	Error            *Error       `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Info             []*WorldInfo `protobuf:"bytes,2,rep,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *WorldsResponse) Reset()         { *m = WorldsResponse{} }
func (m *WorldsResponse) String() string { return proto.CompactTextString(m) }
func (*WorldsResponse) ProtoMessage()    {}

func (m *WorldsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *WorldsResponse) GetInfo() []*WorldInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type WorldSettings struct {
	Size             *int32 `protobuf:"varint,1,opt" json:"Size,omitempty"`
	ChunkWidth       *int32 `protobuf:"varint,2,opt" json:"ChunkWidth,omitempty"`
	ChunkHeight      *int32 `protobuf:"varint,3,opt" json:"ChunkHeight,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *WorldSettings) Reset()         { *m = WorldSettings{} }
func (m *WorldSettings) String() string { return proto.CompactTextString(m) }
func (*WorldSettings) ProtoMessage()    {}

func (m *WorldSettings) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *WorldSettings) GetChunkWidth() int32 {
	if m != nil && m.ChunkWidth != nil {
		return *m.ChunkWidth
	}
	return 0
}

func (m *WorldSettings) GetChunkHeight() int32 {
	if m != nil && m.ChunkHeight != nil {
		return *m.ChunkHeight
	}
	return 0
}

type WorldSettingsResponse struct {
	Error            *Error         `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Settings         *WorldSettings `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *WorldSettingsResponse) Reset()         { *m = WorldSettingsResponse{} }
func (m *WorldSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*WorldSettingsResponse) ProtoMessage()    {}

func (m *WorldSettingsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *WorldSettingsResponse) GetSettings() *WorldSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type ChunksResponse struct {
	Error            *Error   `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Chunks           []*Chunk `protobuf:"bytes,2,rep,name=chunks" json:"chunks,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ChunksResponse) Reset()         { *m = ChunksResponse{} }
func (m *ChunksResponse) String() string { return proto.CompactTextString(m) }
func (*ChunksResponse) ProtoMessage()    {}

func (m *ChunksResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ChunksResponse) GetChunks() []*Chunk {
	if m != nil {
		return m.Chunks
	}
	return nil
}

func init() {
}
