// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

package messages

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Error struct {
	Code             *int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Text             *string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}

func (m *Error) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Error) GetText() string {
	if m != nil && m.Text != nil {
		return *m.Text
	}
	return ""
}

type PlainResponse struct {
	Error            *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PlainResponse) Reset()         { *m = PlainResponse{} }
func (m *PlainResponse) String() string { return proto.CompactTextString(m) }
func (*PlainResponse) ProtoMessage()    {}

func (m *PlainResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
}
