// Code generated by protoc-gen-go.
// source: requstbodies.proto
// DO NOT EDIT!

package messages

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BodyGameRegister struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BodyGameRegister) Reset()         { *m = BodyGameRegister{} }
func (m *BodyGameRegister) String() string { return proto.CompactTextString(m) }
func (*BodyGameRegister) ProtoMessage()    {}

func (m *BodyGameRegister) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type BodyPlaceUnit struct {
	X                *int32 `protobuf:"varint,1,opt,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,2,opt,name=y" json:"y,omitempty"`
	Z                *int32 `protobuf:"varint,3,opt,name=z" json:"z,omitempty"`
	UnitType         *int32 `protobuf:"varint,4,opt,name=unitType" json:"unitType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BodyPlaceUnit) Reset()         { *m = BodyPlaceUnit{} }
func (m *BodyPlaceUnit) String() string { return proto.CompactTextString(m) }
func (*BodyPlaceUnit) ProtoMessage()    {}

func (m *BodyPlaceUnit) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *BodyPlaceUnit) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *BodyPlaceUnit) GetZ() int32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *BodyPlaceUnit) GetUnitType() int32 {
	if m != nil && m.UnitType != nil {
		return *m.UnitType
	}
	return 0
}

func init() {
}
